class Const:
    COL_COLOR = "Color"
    COL_TYPE = "Type"
    COL_LATITUDE = "Latitude"
    COL_LONGITUDE = "Longitude"
    COL_DATE = "Date"
    COL_TIME = "Time"
    COL_IMAGE_URL = "ImageURL"
    COL_FEATURE_VECTOR_PATH = "FeatureVectorPath"
    COL_VEHICLE_ID = "VehicleId"